### PR TITLE
Ported to coq-8.8 (and 8.7)

### PR DESCRIPTION
**Pull request by chdoc**
This is the master branch that is compatible with coq-8.8:
- cleaned up the build infrastructure
- resolved most deprecation warnings
- silenced Canonical Structure warnings
- fixed install target

### CODE REVIEW

**Comment by herbelin** [comment]
Thanks a lot @chdoc, for the port and the cleaning. Now merged (manually).

**Comment by chdoc** [comment]
Hello @herbelin , I appreciate your attempt at simplifying/linearizing the history, but we (Damien and I) have already propagated chdoc:master (292f79b9e9ed3cf63cbc858a1745572841beed1e) to our  development repositories and based further work it. So this creates a bit of a mess for us regarding future changes. Would you be willing to use my master branch unchanged, even though it duplicates the three backported commits on the v8.7 branch? The common ancestor is my v8.7.2 tag (c3b8966a847cfcf8323339dfc030236671517bb5)

**Comment by herbelin** [comment]
Hi @chdoc. Sorry, I did not imagine that linearizing the history was a source of problem for you: I just made as we used to do for user contributions in general. Linearizing for me worked automatically by rebasing, so maybe rebasing your branch would work as easily for you as it did for me.

Or it is that there are technical advantages to a non-linerar history that I would not see?

In any case, a possible and maybe simpler alternative, if you are interested, is that we move `relation-algebra` out of `coq-contribs` and that you maintain it on your own, with opam releases at your will. What do you think?

**Comment by chdoc** [comment]
Hi @herbelin , the advantage is not super-great it's just that (including working copies) the commits you rebased are in 5 repositories (two of them on GitHub, most with additional commits on top) and I'd prefer to not rebase our internal development branch on some cherry-picked backports for 8.7. I'd also say we profited greatly from Coq Developers fixing things in the contribs repository, so there is some incentive to keep it there.

**Comment by herbelin** [comment]
Do you mean that your problem can be resolved only by either rewriting the history of your and Damien's master branches or rewriting the history of coq-contribs master branch?

**Comment by chdoc** [comment]
Yes, and Damien and I decided to rewrite the history on our end. So everything is fine now.

**Pull request closed without merging**
